### ISSUE TITLE
[EN] End of Year and New Year's Seasonal Lines

### ISSUE THREAD

**Issue by nonsensed** [KC3Kai/kc3-translations#341]
There are two sets of different seasonal lines for the end of the year:
- End of year cleanup (expected December 26)
- New Year's (released last year on January 1)

So there's a massive set of lines and then a few days later, another massive set of lines.

There are over 200 lines from last year to work through, so this is the largest scale seasonal line job for the entire year. I don't really expect this to work out very well, but whatever.

### Tasks
* [x] **End of Year** lines: Add last year's lines ahead of time
* [x] Post-maintenance verification of **End of Year** lines
(Adding of new End of Year lines in a timely manner won't happen.)
* [x] **New Year's** lines: Add last year's lines ahead of time
* [x] Post-maintenance verification of **New Year's** lines
* [x] Finish adding new line translations

copy/paste-

My process for entering seasonal lines is as follows:
* **Try to have last year's lines entered before the maintenance**. I refer to both the English wiki and wikia for their translated seasonal lines from last year, though I tend to edit them heavily as I add them to kc3.
* **Following the maintenance is the verification phase.** I activate last year's seasonal lines and go through the ships to verify whether there are new lines, misplaced lines, etc. If there's a new line, I add an empty line to prevent the wrong text from appearing. Once this is complete, the subtitles are at least in a state where people won't say "this line seems wrong! Please fix!" I try to have this done as close to the end of the maintenance as possible.
* **The add new lines phase.** I typically wait for the wikia or wiki to translate any new lines, so this can take any amount of time or may never even be completed while the seasonal lines in question are active. At the very least, I probably won't ever solo translate a line without the Japanese text available, if I solo translate at all.

**Comment by nonsensed** [comment]
@dragonjet 

As far as I'm concerned, the end of year seasonal lines on the English side of things are done. But given the situation, meh, do whatever and I won't mind at all lol.

**Comment by dragonjet** [comment]
are the EN lines in game right now? seems we do need an automated mechanism for the timings of then they show up

**Comment by nonsensed** [comment]
Yeah, they're up. One problem now is that in ~30 hours, the seasonal lines will change. The current lines will be gone and the new year's lines will be up instead and I'll be doing the second half of this. This will be in a live update, so the kancolle server won't be going down.

And absolutely anything to help get them up in a timely manner would be great!

**Comment by nonsensed** [comment]
@dragonjet 
Looks like the New Year's lines will go down in a maintenance on January 10. Probably.

So this is basically finished. I've added the new lines but I don't think it's going to matter much if they ever get uploaded to the webstore. Given that updating causes everyone's kc3 to close right now, I'm hesitant about asking for webstore updates on these. THANKS, GOOGLE

Setsubun seasonal lines will come late in the month, no idea exactly when.

Btw that possibility of implementing TL updates without a webstore update is pretty exciting! Looking forward to it if it works out!
